# Generated by Django 4.2.11 on 2024-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_event_host_time_ampm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_host_time_AMPM',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host_time',
            field=models.TimeField(),
        ),
    ]
